const localNotes = [
  {
    id: 1,
    title: "Maths 1....!",
    description: "Comprehensive notes on calculus and algebra",
    subject: "Mathematics",
    year: "1st Year",
    semester: "1st Semester",
    branch: "Electrical Engineering",
    university: "GTU",
    pages: 45,
    url: "https://cdn.jsdelivr.net/gh/nishant0181/MATE-Notes-Storage@main/sem1/engineering-maths-unit1.pdf",
  },
  {
    id: 2,
    title: "Maths 2",
    description: "Comprehensive notes on differential equations and linear algebra",
    subject: "Mathematics",
    year: "2nd Year",
    semester: "2nd Semester",
    branch: "Electrical Engineering",
    university: "GTU",
    pages: 45,
    url: "https://cdn.jsdelivr.net/gh/nishant0181/MATE-Notes-Storage@main/sem1/BE01000021.pdf",
  },
  {
    id: 3,
    title: "Physics 1",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "1st Semester",
    branch: "Electrical Engineering",
    university: "GTU",
    pages: 50,
    url: "https://example.com/physics1-notes",
  },
  {
    id: 4,
    title: "Physics 3",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "2nd Semester",
    branch: "Electrical Engineering",
    university: "GTU",
    pages: 50,
    url: "https://example.com/physics2-notes",
  },
  {
    id: 5,
    title: "Physics 4",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "3rd Semester",
    branch: "Computer Engineering",
    university: "GTU",
    pages: 50,
    url: "https://example.com/physics3-notes",
  },
  {
    id: 6,
    title: "Physics 5",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "4th Semester",
    branch: "Electrical Engineering",
    university: "GTU",
    pages: 50,
    url: "https://example.com/physics4-notes",
  },
  {
    id: 7,
    title: "Physics 6",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "5th Semester",
    branch: "Computer Engineering",
    university: "University of Technology",
    pages: 50,
    url: "https://example.com/physics5-notes",
  },
  {
    id: 8,
    title: "Physics 7",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "2nd Year",
    semester: "6th Semester",
    branch: "Electrical Engineering",
    university: "University of Technology",
    pages: 50,
    url: "https://example.com/physics6-notes",
  },
  {
    id: 9,
    title: "Physics 8",
    description: "Detailed notes on mechanics and thermodynamics",
    subject: "Physics",
    year: "1st Year",
    semester: "7th Semester",
    branch: "Electrical Engineering",
    university: "University of Technology",
    pages: 50,
    url: "https://example.com/physics7-notes",
  },
];

export function getLocalNotes() {
  return localNotes;
}